### ISSUE TITLE
As a user i want to have someone to play against, so that i have someone to play against

### ISSUE THREAD

**Issue by Wilmer-Chas** [RubinAtChas/groupsix#11]

**Comment by RubinAtChas** [comment]
Implement two players, with a terminal close between each turn. That exits your turn with enter and starts your turn with enter. 
Function of the players are the same.
Två spelbräden.
Turordning i spelet.
EN funktion som avgör när spelet är klart/slut.

**Comment by RubinAtChas** [comment]
Tasks för tvåspelarläge i terminalen
Implementera stöd för två spelare

Skapa funktioner för att hantera två spelare, inklusive deras namn och spelstatus.
Skriv kod som möjliggör att växla mellan spelarna under spelets gång.
Utveckla funktioner för att placera skepp för båda spelarna

Låt båda spelarna placera sina skepp på sina egna spelbräden.
Se till att placeringen är dold från motspelaren, t.ex. genom att använda separata spelbrädor för varje spelare.
Skapa en funktion för att spela en runda

Implementera en funktion där en spelare kan skjuta på motståndarens rutnät och ange koordinaterna för skottet.
Kontrollera om skottet träffar eller missar ett skepp och uppdatera spelbrädet därefter.
Hantera turordningen mellan de två spelarna

Implementera logik för att växla tur efter varje skott.
Visa aktuell spelare och deras tillgängliga alternativ under varje tur.
Implementera en funktion för att avgöra när spelet är slut

Skapa logik som kontrollerar om alla skepp för en spelare har blivit sänkta.
Visa ett meddelande som indikerar vinnaren när spelet är över.
